# Generated by Django 5.2 on 2025-04-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handover_id', models.CharField(max_length=11)),
                ('shift_date', models.DateTimeField()),
                ('shift', models.CharField(max_length=2)),
                ('dispatcher_name', models.CharField()),
                ('chief_duty_name', models.CharField()),
                ('shift_highlights', models.TextField()),
                ('non_standard_flights', models.JSONField()),
                ('naifr', models.JSONField()),
                ('aog', models.JSONField()),
                ('comat_flights', models.JSONField()),
                ('fob_created_aog', models.BooleanField()),
                ('remarks_created_com', models.BooleanField()),
                ('weather_issues', models.TextField()),
                ('operational_notams', models.TextField()),
                ('enroute_weather', models.TextField()),
                ('mels', models.TextField()),
                ('cdd_network_summary', models.TextField()),
                ('misc', models.TextField()),
                ('it_issues', models.TextField()),
                ('navblue_tickets', models.TextField()),
                ('procedural_changes', models.TextField()),
            ],
        ),
    ]
