# Generated by Django 5.2 on 2025-04-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='aog',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='cdd_network_summary',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='comat_flights',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='enroute_weather',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='fob_created_aog',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='it_issues',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='mels',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='misc',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='naifr',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='navblue_tickets',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='operational_notams',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='procedural_changes',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='remarks_created_com',
        ),
        migrations.RemoveField(
            model_name='handover',
            name='weather_issues',
        ),
    ]
