# Generated by Django 5.2 on 2025-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0003_alter_handover_shift_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='chief_duty_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='handover',
            name='dispatcher_name',
            field=models.CharField(max_length=100),
        ),
    ]
