# Generated by Django 5.2 on 2025-04-21 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0004_alter_handover_chief_duty_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='non_standard_flights',
        ),
    ]
