# Generated by Django 5.2 on 2025-04-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0005_remove_handover_non_standard_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='id',
        ),
        migrations.AlterField(
            model_name='handover',
            name='handover_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
