# Generated by Django 5.2 on 2025-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0006_remove_handover_id_alter_handover_handover_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='non_standard_flights',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
