# Generated by Django 5.2 on 2025-04-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0007_handover_non_standard_flights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handover',
            name='non_standard_flights',
        ),
        migrations.CreateModel(
            name='NonStandardFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_standard_flights', to='dispatchers.handover')),
            ],
        ),
    ]
