# Generated by Django 5.2 on 2025-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0008_remove_handover_non_standard_flights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='non_standard_flights',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='NonStandardFlight',
        ),
    ]
