# Generated by Django 5.2 on 2025-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0011_handover_non_standard_flights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='naifr',
            field=models.JSONField(default=2022),
            preserve_default=False,
        ),
    ]
