# Generated by Django 5.2 on 2025-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0012_handover_naifr'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='aog',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='handover',
            name='naifr',
            field=models.JSONField(default=list),
        ),
    ]
