# Generated by Django 5.2 on 2025-04-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0013_handover_aog_alter_handover_naifr'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='comat_flights',
            field=models.JSONField(default=list),
        ),
    ]
