# Generated by Django 5.2 on 2025-04-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0014_handover_comat_flights'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='fob_created_aog',
            field=models.BooleanField(default=False),
        ),
    ]
