# Generated by Django 5.2 on 2025-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0015_handover_fob_created_aog'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='remarks_created_com',
            field=models.BooleanField(default=False),
        ),
    ]
