# Generated by Django 5.2 on 2025-04-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0016_handover_remarks_created_com'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='weather_issues',
            field=models.TextField(blank=True, null=True),
        ),
    ]
