# Generated by Django 5.2 on 2025-04-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0017_handover_weather_issues'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='cdd_network_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='enroute_weather',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='it_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='mels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='misc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='navblue_tickets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='operational_notams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='handover',
            name='procedural_changes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
