# Generated by Django 5.2 on 2025-04-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0018_handover_cdd_network_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover',
            name='fuel_payload_critical',
            field=models.TextField(blank=True, null=True),
        ),
    ]
