# Generated by Django 5.2 on 2025-04-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0019_handover_fuel_payload_critical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover',
            name='handover_id',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
